(define (simpsons-rule f a b n)
  (define (yk k h)
    (f (+ a (* k h))))
  (define (termk k h)
    (cond ((= k 0) (yk k h))
          ((= k n) (yk k h))
          ((even? k) (* 2 (yk k h)))
          ((odd? k) (* 4 (yk k h)))))
  (define (sum k h)
    (cond ((> k n) 0)
          (else (+ (termk k h) (sum (+ 1 k) h)))
          ))
  (define (get-h)
    (/ (- b a) n))
  (* (/ (get-h) 3) (sum 0 (get-h)))
  ;;(sum 0 (get-h))
  )


(define (cube a)
  (* a a a))
(simpsons-rule cube 0.0 1.0 100)
(simpsons-rule cube 0.0 1.0 1000)
